package n1ex3;

import org.junit.Test;

class AppTest {


	@Test(expected = ArrayIndexOutOfBoundsException.class)
	public void atTestThrowException() throws Exception{
	    
		App apptest = new App(2); //inicialitzem la classe 

	    apptest.indexArray(8); //Cridem al métode per tal que ens digui si hi ha un element a la posició 8 per provocar l'error 


	}
}
